export const styles = {
  container: {
    backgroundColor: "#f0f5ff", // Light blue background for better contrast
    minHeight: "100vh",
    padding: "32px 20px",
    fontFamily:
      "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    color: "#333",
    lineHeight: 1.5,
  },
  vstack: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    maxWidth: "700px",
    margin: "0 auto",
    backgroundColor: "white",
    padding: "32px",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.08)",
  },
  heading: {
    fontSize: "2rem",
    fontWeight: "700",
    textAlign: "center",
    marginBottom: "24px",
    color: "#2563eb", // Blue shade for heading
    borderBottom: "2px solid #e5e7eb",
    paddingBottom: "16px",
  },
  input: {
    padding: "12px 16px",
    fontSize: "1rem",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    backgroundColor: "white",
    width: "100%",
    transition: "border-color 0.2s ease",
  },
  button: {
    padding: "12px 20px",
    fontSize: "1rem",
    fontWeight: "600",
    borderRadius: "6px",
    cursor: "pointer",
    border: "none",
    transition: "all 0.2s ease",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPrimary: {
    backgroundColor: "#2563eb", // Blue
    color: "white",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
  },
  buttonOutline: {
    border: "1px solid #2563eb",
    color: "#2563eb",
    backgroundColor: "white",
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },
  formGroup: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    marginBottom: "8px",
    fontWeight: "600",
    color: "#4b5563",
  },
  textarea: {
    width: "100%",
    padding: "12px 16px",
    fontSize: "1rem",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    minHeight: "100px",
    resize: "vertical",
    fontFamily: "inherit",
  },
  fileUpload: {
    border: "2px dashed #d1d5db",
    borderRadius: "8px",
    padding: "24px",
    textAlign: "center",
    color: "#6b7280",
    cursor: "pointer",
    transition: "all 0.2s ease",
    backgroundColor: "#f9fafb",
  },
  fileUploadHover: {
    borderColor: "#93c5fd",
    backgroundColor: "#f0f7ff",
    color: "#2563eb",
  },
  previewArea: {
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "16px",
    backgroundColor: "white",
    marginTop: "16px",
  },
  previewTitle: {
    fontSize: "1.1rem",
    fontWeight: "600",
    marginBottom: "12px",
    color: "#374151",
  },
  previewWrap: {
    display: "flex",
    flexWrap: "wrap",
    gap: "16px",
  },
  previewItem: {
    position: "relative",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    borderRadius: "8px",
    overflow: "hidden",
  },
  previewImage: {
    width: "120px",
    height: "120px",
    objectFit: "cover",
    borderRadius: "6px",
    border: "1px solid #e5e7eb",
  },
  removeButton: {
    position: "absolute",
    top: "-8px",
    right: "-8px",
    background: "#ef4444",
    color: "white",
    border: "none",
    borderRadius: "50%",
    width: "24px",
    height: "24px",
    fontSize: "14px",
    lineHeight: "24px",
    textAlign: "center",
    cursor: "pointer",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.2)",
    zIndex: 10,
  },
  resultArea: {
    marginTop: "24px",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    overflow: "hidden",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  resultTitle: {
    backgroundColor: "#f9fafb",
    padding: "12px 16px",
    fontWeight: "600",
    borderBottom: "1px solid #e5e7eb",
    color: "#374151",
  },
  resultImage: {
    display: "block",
    width: "100%",
    maxHeight: "500px",
    objectFit: "contain",
    background: "#f0f0f0",
    padding: "12px",
  },
  radioContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginBottom: "20px",
    padding: "16px",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    backgroundColor: "#f9fafb",
  },
  radioOption: {
    padding: "16px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "flex-start",
  },
  radioOptionSelected: {
    backgroundColor: "#2563eb",
    color: "white",
  },
  radioOptionUnselected: {
    backgroundColor: "white",
    border: "1px solid #d1d5db",
  },
  radioLabel: {
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
  },
  radioDescription: {
    fontSize: "0.875rem",
    marginTop: "4px",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px",
    color: "#6b7280",
  },
  loadingSpinner: {
    border: "4px solid rgba(0, 0, 0, 0.1)",
    borderLeft: "4px solid #2563eb",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    animation: "spin 1s linear infinite",
    marginBottom: "16px",
  },
  errorMessage: {
    color: "#dc2626",
    backgroundColor: "#fee2e2",
    padding: "12px 16px",
    borderRadius: "6px",
    marginBottom: "16px",
    fontSize: "0.875rem",
    fontWeight: "500",
  },
  successMessage: {
    color: "#059669",
    backgroundColor: "#d1fae5",
    padding: "12px 16px",
    borderRadius: "6px",
    marginBottom: "16px",
    fontSize: "0.875rem",
    fontWeight: "500",
  },
};
